spring.application.name=SpringBootApiIntegration

#Port number
server.port = 8584

#Context path name
server.servlet.context-path = /ThirdPartyAPIIntegration

#Information about third party
wati.api.token = Type token
wati.api.url = https://app-server.wati.io/api/v1/sendTemplateMessage

